version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lumen-app
    container_name: ksmanajemen-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-manifest/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ksmanajemen-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: ksmanajemen-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8003:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-manifest/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - ksmanajemen-network

#Docker Networks
networks:
  ksmanajemen-network:
    driver: bridge
